/**
 * Torq domain types: a Strong-style workout tracker.
 * Every synced row carries `id` + `updatedAt` (epoch ms) for last-write-wins
 * delta sync (see lib/sync.ts and supabase/schema.sql).
 */

export type Unit = "kg" | "lb";

export type SetType = "normal" | "warmup" | "drop" | "failure";

export type BodyPart =
  | "chest"
  | "back"
  | "legs"
  | "shoulders"
  | "arms"
  | "core"
  | "olympic"
  | "cardio"
  | "other";

export type Equipment =
  | "barbell"
  | "dumbbell"
  | "machine"
  | "cable"
  | "bodyweight"
  | "kettlebell"
  | "band"
  | "other";

/** One movement in the library (Bench Press, Squat…). */
export interface Exercise {
  id: string;
  name: string;
  bodyPart: BodyPart;
  equipment: Equipment;
  /** ExerciseDB id when imported from the bundled catalog (keys DB_GIFS). */
  dbId?: string;
  notes?: string;
  /** Per-exercise warm-up formula, remembered from the warm-up dialog. */
  warmup?: WarmupRow[];
  updatedAt: number;
}

/**
 * One row of a warm-up ramp: either the empty bar, or a percentage of the
 * work set. Stored on the Exercise so the ramp you tuned for squats doesn't
 * follow you to curls.
 */
export interface WarmupRow {
  /** True for the "Bar x N" row: a fixed weight, not a percentage. */
  bar?: boolean;
  /** Percentage of the work set, when `bar` is not set. */
  pct?: number;
  reps: number;
}

/** One logged set: weight × reps (weight in the user's unit). */
export interface WorkoutSet {
  type: SetType;
  weight: number;
  reps: number;
  /** Ticked off during an active session. */
  done: boolean;
  /** Per-set rest override in seconds (falls back to Settings.restSec). */
  restSec?: number;
  /**
   * When this set was ticked, in epoch ms. Recorded from 2026-08-11.
   *
   * It is the richest signal a barbell app can collect about itself: real
   * rest intervals rather than planned ones, whether a session was lived or
   * backfilled afterwards, and pacing that decays as the sets get hard. That
   * feeds honest rest analytics and the realism half of the trust ladder in
   * FEATURES.md. Recorded from the day it shipped because history that was
   * never captured can never be scored later.
   *
   * Optional forever: every set logged before this date has none, and a set
   * un-ticked drops it.
   */
  doneAt?: number;
  /** Live-session marker: the weight was prefilled by the progression
   *  engine (up = increase, down = deload). Cleared on edit; stripped when
   *  the workout finishes. */
  suggested?: "up" | "down";
}

/** One exercise inside a workout/routine with its sets. */
/** Live-session focus metric shown as a pill next to the exercise name. */
export type FocusMetric = "volume" | "volumeIncrease" | "reps" | "weightReps";

export interface WorkoutEntry {
  exerciseId: string;
  sets: WorkoutSet[];
  notes?: string;
  focusMetric?: FocusMetric;
}

/** A reusable workout template (Strong's "Routine"). */
export interface Routine {
  id: string;
  name: string;
  entries: WorkoutEntry[];
  /** Generated by the training-plan wizard (replaced when the plan rebuilds). */
  plan?: boolean;
  /** Scheduled weekday for plan routines (0 = Sunday … 6 = Saturday). */
  weekday?: number;
  /** Hidden from the Start-Workout grid (menu → Archive). */
  archived?: boolean;
  updatedAt: number;
}

/** Training-plan preferences captured by onboarding (see lib/plan.ts). */
export type PlanGoal = "muscle" | "lean" | "strength" | "fit";

export interface PlanPrefs {
  goal: PlanGoal;
  /** Chosen training weekdays (0 = Sunday … 6 = Saturday), 2-6 of them,
   *  the rest are rest days. */
  weekdays: number[];
  /** Muscle groups to emphasize (extra volume + accessory slots). */
  focus: BodyPart[];
  createdAt: number;
}

/** A logged (or in-progress) workout session. */
export interface Workout {
  id: string;
  name: string;
  /** Routine it was started from, if any. */
  routineId?: string;
  startedAt: number;
  /** Unset while the session is active. */
  endedAt?: number;
  entries: WorkoutEntry[];
  notes?: string;
  updatedAt: number;
}

/** A body measurement point (weight, body fat, chest…). */
export interface Measurement {
  id: string;
  kind: string;
  value: number;
  unit: string;
  at: number;
  updatedAt: number;
}

export interface Settings {
  /**
   * The gym's bar and plate set, for plate math. Undefined means the
   * standard olympic set for the display unit (see lib/plates.ts), which is
   * right for most gyms and keeps this optional forever.
   */
  barWeight?: number;
  plates?: number[];
  /**
   * Epoch ms until which a deload week is running. While it is in the
   * future, `startWorkout` prefills working weights at DELOAD_FACTOR.
   * Set by accepting the fatigue check on Home; expires on its own.
   */
  deloadUntil?: number;
  id: "settings";
  name: string;
  unit: Unit;
  /** Default rest timer in seconds. */
  restSec: number;
  /** Body profile for calorie estimation (see lib/calories.ts). */
  sex?: "male" | "female";
  birthYear?: number;
  heightCm?: number;
  /** Fallback body weight in kg when no "Body weight" measurement is logged. */
  weightKg?: number;
  /** Daily calorie-burn goal for the Home dashboard (default in lib/stats
   *  kcalGoal; prefilled per plan goal). Other targets are plan-derived. */
  kcalGoal?: number;
  /** Training plan built by onboarding (routines carry the actual days). */
  plan?: PlanPrefs;
  /** Welcome flow finished (or skipped). */
  onboarded?: boolean;
  /** Day (local midnight ms) whose streak celebration was already shown,
   *  the Home modal auto-pops once per trained day. */
  streakCelebratedDay?: number;
  /** Profile picture kept on this phone (document dir). Always set once a
   *  picture is chosen, even with no account. */
  avatarUri?: string;
  /** Public URL of the uploaded copy (Supabase Storage). Preferred for
   *  display, because it is the one that is valid on every device. */
  avatarUrl?: string;
  /** Sound effects on set-done / rest countdown / finish. Default ON
   *  (undefined counts as on, so existing installs get them). */
  sound?: boolean;
  updatedAt: number;
}

export const DEFAULT_SETTINGS: Settings = {
  id: "settings",
  name: "",
  unit: "kg",
  restSec: 120,
  updatedAt: 0,
};

export function uid(): string {
  return (
    Date.now().toString(36) + Math.random().toString(36).slice(2, 10)
  );
}

/** Total volume (weight × reps) of completed sets in a workout. */
export function workoutVolume(w: Workout): number {
  return w.entries.reduce(
    (sum, e) =>
      sum + e.sets.reduce((s, set) => s + (set.done ? set.weight * set.reps : 0), 0),
    0,
  );
}

/** Count of completed sets. */
export function workoutSets(w: Workout): number {
  return w.entries.reduce((sum, e) => sum + e.sets.filter((s) => s.done).length, 0);
}
